#!/usr/bin/env bash
# This script prints Best School 10 times and says Hi on iteration 9

count=1
while [ "$count" -le 10 ]
do
    echo "Best School"
    if [ "$count" -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1))
done
